PATH=$(CMTROOT)/$(CMTBIN):/usr/local/bin:.:/usr/local/bin:/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/nfs/slac/g/USAData1/USA/ciao_2.2/ots/saord/bin:/nfs/slac/g/USAData1/USA/ciao_2.2/contrib:/nfs/slac/g/USAData1/USA/ciao_2.2/bin:/nfs/slac/g/USAData1/USA/lheasoft/Linux_2.2_i686/scripts:/nfs/slac/g/USAData1/USA/lheasoft/Linux_2.2_i686/bin:/usr/local/bin:/u1/local/mozilla:/u1/local/test/qt-x11-free-3.1.2/bin:/u1/jchiang/root/bin:/u1/jchiang/bin:/u1/jchiang/OpenOffice.org1.0.2:/u1/local/bin:/u1/jchiang/local/bin:/u/gl/jchiang/bin:.:/usr/local/bin:/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/usr/local/bin:.:/usr/local/bin:/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/usr/local/bin:.:/usr/local/bin:/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/bin:/usr/bin:/usr/bin/X11:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/afs/slac.stanford.edu/i386_linux24/usr/local/bin:/usr/X11R6/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/afs/slac.stanford.edu/i386_linux24/usr/local/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/afs/slac.stanford.edu/i386_linux24/usr/local/bin:/nfs/slac/g/USAData1/USA/bin/Linux:/nfs/slac/g/USAData1/USA/scripts:/afs/slac/g/ek/rsi/idl/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/afs/slac.stanford.edu/i386_linux24/usr/local/bin::$(ROOTSYS)/bin
CLASSPATH=$(CMTROOT)/java
debug_option=-g
cdebugflags=$(debug_option)
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags)
ppcmd=-I
cpp=g++-2.95.3
cppdebugflags=$(debug_option)
cppflags=-pipe -ansi -W -Wall  -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppoptions) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(makeLinkMap) $(linkdebug)
cpplink=$(cpp)   $(cpplinkflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=$(CMTROOT)/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++-2.95.3
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=$(CMTROOT)/$(CMTBIN)/cmt.exe
tags=$(CMTEXTRATAGS)
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
mkdir=mkdir
BINDIR=rh72_gcc2953
cppoptions=$(cppdebugflags_s)
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
linkdebug=-g 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC  -ldl 
libraryshr_linkopts=-fPIC -ldl 
GlastMain=$(GLASTPOLICYROOT)/src/GlastMain.cxx
TestGlastMain=$(GLASTPOLICYROOT)/src/TestGlastMain.cxx
rootTuple_linkopts=-L$(rootTupleDir) -lrootTuple 
fitsGen_linkopts=-L$(fitsGenDir) -lfitsGen 
PLATARCHdef=rh61_gcc2952
PLATARCH=rh72_gcc2953
EXTPACK_DIR=$(GLAST_EXT)
ROOT_DIR=$(EXTPACK_DIR)/ROOT
PYTHON_DIR=$(EXTPACK_DIR)/Python
XERCES_DIR=$(EXTPACK_DIR)/Xerces-C
BOOST_DIR=$(EXTPACK_DIR)/Boost
AIDA_DIR=$(EXTPACK_DIR)/AIDA
CLHEP_DIR=$(EXTPACK_DIR)/CLHEP
HTL_DIR=$(EXTPACK_DIR)/HTL
NAGC_DIR=$(EXTPACK_DIR)/Nag_C
GSL_DIR=$(EXTPACK_DIR)/GSL
GEANT4_DIR=$(EXTPACK_DIR)/geant4
MYSQL_DIR=$(EXTPACK_DIR)/MYSQL
ROOT_native_version=v3.04.02
ROOT_PATH=$(ROOT_DIR)/$(ROOT_native_version)/root
ROOTSYS=/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root
dict=../dict/
rootcint=rootcint
ROOT_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lpthread -lm -ldl -rdynamic  -lTreePlayer -lProof -lGX11 
ROOT_linkopts=$(ROOT_libs)
ROOT_cppflagsEx=$(ppcmd) "$(ROOT_PATH)/include" -DUSE_ROOT
LD_LIBRARY_PATH=/nfs/slac/g/USAData1/USA/ciao_2.2/lib:/nfs/slac/g/USAData1/USA/lheasoft/Linux_2.2_i686/lib:/u1/jchiang/local/lib:/u1/local/test/qt-x11-free-3.1.2/lib:.:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/usr/local/lib/python2.2/config:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/gaudi/v11r4p0/GaudiKernel/v13r2/Linux-i686:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/gaudi/v11r4p0/GaudiAlg/v6r3p1/Linux-i686:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/usr/local/lib/python2.2/config:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/u/gl/jchiang/lib:/u1/local/lib:/u1/jchiang/root/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/usr/local/lib/python2.2/config:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/nfs/slac/g/USAData1/USA/pgplot/Linux:/nfs/slac/g/USAData1/USA/lib/Linux:/usr/local/cfitsio/lib/:.:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/usr/local/lib/python2.2/config:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/u1/jchiang/SciTools/dev/xml/v4r3p1/rh72_gcc2953:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/CLHEP/1.8.0.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/HTL/1.3.1.2/lib:/u1/jchiang/SciTools/dev/xmlUtil/v2r10p2/rh72_gcc2953:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib::/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root/bin:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root/lib:$(CFITSIO_DIR)/lib
Goodi_linkopts=-L$(GoodiDir) -lGoodi 
facilities_linkopts=-L$(facilitiesDir) -lfacilities 
cfitsio_native_version=v2410
CFITSIO_DIR=$(GLAST_EXT)/cfitsio/v2410
cfitsio_libs=-L$(CFITSIO_DIR)/lib -lcfitsio 
cfitsio_linkopts=$(cfitsio_libs) 
fitsGen_cppflags=-I ../src -g -pedantic 
makeFT1stamps=makeFT1.stamp
makeFT2stamps=makeFT2.stamp
INFILES=/u1/jchiang/SciTools/dev/Goodi/v2r1p8/Data
GlastPolicyDir=$(GLASTPOLICYROOT)/$(BINDIR)
rootTupleDir=$(ROOTTUPLEROOT)/$(BINDIR)
RootPolicyDir=$(ROOTPOLICYROOT)/$(BINDIR)
facilitiesDir=$(FACILITIESROOT)/$(BINDIR)
GoodiDir=$(GOODIROOT)/$(BINDIR)
fitsGenDir=$(FITSGENROOT)/$(BINDIR)
tag=rh72_gcc2953
fitsGen_tag=$(tag)
FITSGENROOT=/u1/jchiang/SciTools/dev/fitsGen/v0
PACKAGE_ROOT=$(FITSGENROOT)
fitsGen_root=../../../fitsGen/v0
FITSGENVERSION=v0
srcdir=../src
bin=../$(fitsGen_tag)/
javabin=../classes/
mgrdir=cmt
version=v0
package=fitsGen
rootTuple_tag=$(tag)
ROOTTUPLEROOT=/u1/jchiang/SciTools/dev/rootTuple/v0r4p0
rootTuple_root=../../../rootTuple/v0r4p0
ROOTTUPLEVERSION=v0r4p0
Goodi_tag=$(tag)
GOODIROOT=/u1/jchiang/SciTools/dev/Goodi/v2r1p8
Goodi_root=../../../Goodi/v2r1p8
GOODIVERSION=v2r1p8
RootPolicy_tag=$(tag)
ROOTPOLICYROOT=/u1/jchiang/SciTools/dev/RootPolicy/v2r1p2
RootPolicy_root=../../../RootPolicy/v2r1p2
ROOTPOLICYVERSION=v2r1p2
facilities_tag=$(tag)
FACILITIESROOT=/u1/jchiang/SciTools/dev/facilities/v2r7p2
facilities_root=../../../facilities/v2r7p2
FACILITIESVERSION=v2r7p2
GlastPolicy_tag=$(tag)
GLASTPOLICYROOT=/u1/jchiang/SciTools/dev/GlastPolicy/v5r3
GlastPolicy_root=../../../GlastPolicy/v5r3
GLASTPOLICYVERSION=v5r3
ROOT_tag=$(tag)
ROOTROOT=/u1/jchiang/SciTools/dev/IExternal/ROOT/v2r30402p0
ROOT_root=../../../IExternal/ROOT/v2r30402p0
ROOTVERSION=v2r30402p0
ExternalLibs_tag=$(tag)
EXTERNALLIBSROOT=/u1/jchiang/SciTools/dev/IExternal/ExternalLibs/v4r0p3
ExternalLibs_root=../../../IExternal/ExternalLibs/v4r0p3
EXTERNALLIBSVERSION=v4r0p3
cfitsio_tag=$(tag)
CFITSIOROOT=/u1/jchiang/SciTools/dev/IExternal/cfitsio/v1r2410p1
cfitsio_root=../../../IExternal/cfitsio/v1r2410p1
CFITSIOVERSION=v1r2410p1
use_requirements=requirements $(CMTROOT)/mgr/requirements $(ROOTTUPLEROOT)/cmt/requirements $(GOODIROOT)/cmt/requirements $(ROOTPOLICYROOT)/cmt/requirements $(FACILITIESROOT)/cmt/requirements $(GLASTPOLICYROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(EXTERNALLIBSROOT)/cmt/requirements $(CFITSIOROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(ROOTTUPLEROOT)" $(ppcmd)"$(GOODIROOT)" $(ppcmd)"$(FACILITIESROOT)" $(ppcmd)"$(GLASTPOLICYROOT)" $(ppcmd)"$(ROOT_PATH)/include" $(ppcmd)"$(CFITSIO_DIR)/include" 
use_fincludes= $(use_includes)
use_stamps= $(fitsGen_stamps)  $(rootTuple_stamps)  $(Goodi_stamps)  $(RootPolicy_stamps)  $(facilities_stamps)  $(GlastPolicy_stamps)  $(ROOT_stamps)  $(ExternalLibs_stamps)  $(cfitsio_stamps) 
use_cflags=  $(fitsGen_cflags)  $(rootTuple_cflags)  $(Goodi_cflags)  $(RootPolicy_cflags)  $(facilities_cflags)  $(GlastPolicy_cflags)  $(ROOT_cflags)  $(ExternalLibs_cflags)  $(cfitsio_cflags) 
use_pp_cflags=  $(fitsGen_pp_cflags)  $(rootTuple_pp_cflags)  $(Goodi_pp_cflags)  $(RootPolicy_pp_cflags)  $(facilities_pp_cflags)  $(GlastPolicy_pp_cflags)  $(ROOT_pp_cflags)  $(ExternalLibs_pp_cflags)  $(cfitsio_pp_cflags) 
use_cppflags=  $(fitsGen_cppflags)  $(rootTuple_cppflags)  $(Goodi_cppflags)  $(RootPolicy_cppflags)  $(facilities_cppflags)  $(GlastPolicy_cppflags)  $(ROOT_cppflags)  $(ExternalLibs_cppflags)  $(cfitsio_cppflags) 
use_pp_cppflags=  $(fitsGen_pp_cppflags)  $(rootTuple_pp_cppflags)  $(Goodi_pp_cppflags)  $(RootPolicy_pp_cppflags)  $(facilities_pp_cppflags)  $(GlastPolicy_pp_cppflags)  $(ROOT_pp_cppflags)  $(ExternalLibs_pp_cppflags)  $(cfitsio_pp_cppflags) 
use_fflags=  $(fitsGen_fflags)  $(rootTuple_fflags)  $(Goodi_fflags)  $(RootPolicy_fflags)  $(facilities_fflags)  $(GlastPolicy_fflags)  $(ROOT_fflags)  $(ExternalLibs_fflags)  $(cfitsio_fflags) 
use_pp_fflags=  $(fitsGen_pp_fflags)  $(rootTuple_pp_fflags)  $(Goodi_pp_fflags)  $(RootPolicy_pp_fflags)  $(facilities_pp_fflags)  $(GlastPolicy_pp_fflags)  $(ROOT_pp_fflags)  $(ExternalLibs_pp_fflags)  $(cfitsio_pp_fflags) 
use_linkopts=  $(fitsGen_linkopts)  $(rootTuple_linkopts)  $(Goodi_linkopts)  $(RootPolicy_linkopts)  $(facilities_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts)  $(cfitsio_linkopts) 
use_libraries= $(rootTuple_libraries)  $(Goodi_libraries)  $(RootPolicy_libraries)  $(facilities_libraries)  $(GlastPolicy_libraries)  $(ROOT_libraries)  $(ExternalLibs_libraries)  $(cfitsio_libraries) 
includes= $(ppcmd)"$(FITSGENROOT)" $(use_includes)
fincludes= $(includes)
fitsGen_use_linkopts=  $(fitsGen_linkopts)  $(rootTuple_linkopts)  $(Goodi_linkopts)  $(RootPolicy_linkopts)  $(facilities_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts)  $(cfitsio_linkopts) 
makeFT1_use_linkopts=  $(fitsGen_linkopts)  $(rootTuple_linkopts)  $(Goodi_linkopts)  $(RootPolicy_linkopts)  $(facilities_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts)  $(cfitsio_linkopts) 
makeFT2_use_linkopts=  $(fitsGen_linkopts)  $(rootTuple_linkopts)  $(Goodi_linkopts)  $(RootPolicy_linkopts)  $(facilities_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts)  $(cfitsio_linkopts) 
constituents= fitsGen makeFT1 makeFT2 
all_constituents= $(constituents)
constituentsclean= makeFT2clean makeFT1clean fitsGenclean 
all_constituentsclean= $(constituentsclean)
